eis:
# collection: public.eis_fire_snapshot_perimeter_nrt
# collection: public.eis_fire_lf_perimeter_archive
  collection: public.eis_fire_lf_perimeter_nrt
  bbox: ['-175.0', '20.0', '-60.0', '70.0']
# bbox: ['-127.0', '20.0', '-65.0', '49.0']
  min_area: 0.0 # minimum area of fire (km+2)
  min_duration: 1 # minimum duration of fire (days)
  limit: 9999 # minimum number of locations
# time_window: P21D
  time_window: P13D
  shape_file: /discover/nobackup/jardizzo/maps/fires/eis/eis_%Y%m%d
  fluid_file: eis_fluid.yml
  csv_file: eis.csv

firms:
  collection:
  bbox: [-140.0, 20.0, -60.0, 60.0]
  min_area: 0.001 # minimum area of fire (km+2)
  min_duration: 2 # minimum duration of fire (days)
  limit: 3000 # minimum number of locations
  time_window: P6D
  shape_file: /discover/nobackup/jardizzo/maps/fires/firms/firms_%Y%m%d
  fluid_file: firms_fluid.yml
  csv_file: firms.csv
  json_file: /discover/nobackup/jardizzo/maps/fires/firms/firms_%Y%m%d.json

eonet:
  collection:
  bbox: [-140.0, 20.0, -60.0, 60.0]
  min_area: 75 # minimum area of fire (acres+2)
  min_duration: 2 # minimum duration of fire (days)
  limit: 3000 # minimum number of locations
  time_window: P6D
  shape_file: /discover/nobackup/jardizzo/maps/fires/eonet/eonet_%Y%m%d
  fluid_file: /discover/nobackup/jardizzo/maps/fires/eonet/eonet_%Y%m%d/eonet_%Y%m%d.yml
  csv_file: eonet.csv
